[book]
authors = ["Anoma Contributors"]
language = "en"
multilingual = false
src = "src"
title = "Anoma Specifications"

[output.html]
edit-url-template = "https://github.com/anoma/specs/edit/main/{path}"
git-repository-url = "https://github.com/anoma/specs"
additional-css = ["assets/custom.css"]
additional-js = ["assets/mermaid.min.js", "assets/mermaid-init.js"]

[output.html.fold]
enable = true
level = 0

[output.html.search]
expand = true

[output.linkcheck]

[preprocessor]

[preprocessor.katex]
after = ["links"]
macros = "src/macros.txt"
