[book]
authors = ["Anoma Contributors"]
language = "en"
multilingual = false
site-url = "https://specs.anoma.network"
src = "src"
title = "Anoma Specifications"

[output.html]
edit-url-template = "https://github.com/anoma/specs/edit/master/{path}"
git-repository-url = "https://github.com/anoma/specs"
additional-css = ["assets/custom.css"]
additional-js = ["assets/mermaid.min.js", "assets/mermaid-init.js"]
# mathjax-support = true

[output.html.fold]
enable = true
level = 1

[output.html.search]
expand = true

[output.katex]

[output.linkcheck]

[output.pdf]

[preprocessor]

[preprocessor.katex]
macros = "src/macros.latex"

[preprocessor.mermaid]
command = "mdbook-mermaid"
